Added --name parameter to allow setting the name of documented module
lampepfl/scala3doc pull request #106
Opened 2020-08-12 13:16 UTC by pikinier20

closes #98

2020-08-13 13:32 UTC, romanowski requested changes

2020-08-13 13:32 UTC, romanowski commented on src/main/scala/dotty/dokka/Main.scala
> +    @COption(name="--name", aliases = Array("-n"), usage="Name of documented project")
IMHO it should be mandatory

2020-08-13 13:33 UTC, romanowski commented
I forgot to add to review but we also need to update documentation (yes, we have a documentation for cmd :) )

2020-08-14 09:17 UTC, pikinier20 commented on src/main/scala/dotty/dokka/Main.scala
> +    @COption(name="--name", aliases = Array("-n"), usage="Name of documented project")
Added `required` flag

2020-08-14 09:19 UTC, pikinier20 commented
Updated documentation, idk if "name of module in generated documentation" is proper term

2020-08-20 19:06 UTC, romanowski approved these changes

2020-08-21 08:39 UTC, merged