Show missing implicitly added members, add some tests
lampepfl/scala3doc pull request #211
Opened 2020-10-19 14:21 UTC by pikinier20

2020-10-19 16:07 UTC, romanowski requested changes
We should expand information in `Kind.Implicit`.

Also few small code style suggestions.

2020-10-19 16:07 UTC, romanowski commented on src/main/scala/tests/implicitConversions/A.scala
> +        = ???
Nitpick: We don't need `= ???` with comments :)

2020-10-19 16:07 UTC, romanowski commented on src/main/scala/dotty/dokka/tasty/ClassLikeSupport.scala
> +      else if methodSymbol.flags.is(Flags.Implicit) then
The origin is a bit misleading [here](https://scala3doc.s3.eu-central-1.amazonaws.com/pr-211/self/scala3doc/tests/implicitConversions/-clazz-a/index.html). It should said  that conversion comes from `object A` and coverts to `class B` - so we would need to change  what is stored in `conversion`

2020-10-19 16:07 UTC, romanowski commented on src/main/scala/dotty/dokka/transformers/ImplicitMembersExtensionTransformer.scala
> +            val parentCompanions = c.parents.map { p =>
Nitpick:

```
val allParents =c.parents.flatMap(p => classlikeMap.get(p.dri))
val parentsCompanions = allParents.flatMap{ _ match 
    case cls: DClasslike => ClasslikeExtension.getFrom(cls).flatMap(_.companion).map(classlikeMap)
    case _ => None
}

``

2020-10-22 11:01 UTC, pikinier20 commented on src/main/scala/tests/implicitConversions/A.scala
> +        = ???
removed

2020-10-22 11:01 UTC, pikinier20 commented on src/main/scala/dotty/dokka/tasty/ClassLikeSupport.scala
> +      else if methodSymbol.flags.is(Flags.Implicit) then
Extended information stored in ImplicitConversion and ImplictlyAddedBy

2020-10-22 11:02 UTC, pikinier20 commented on src/main/scala/dotty/dokka/transformers/ImplicitMembersExtensionTransformer.scala
> +            val parentCompanions = c.parents.map { p =>
Refactored

2020-10-22 19:31 UTC, romanowski approved these changes
I've asked to change a comment plus few style-related nitpicks

2020-10-22 19:31 UTC, romanowski commented on src/main/scala/dotty/dokka/transformers/ImplicitMembersExtensionTransformer.scala
> +            val allParents = c.parents.flatMap { p =>
Nitpick: it should be oneliner

2020-10-22 19:31 UTC, romanowski commented on src/main/scala/dotty/dokka/transformers/ImplicitMembersExtensionTransformer.scala
> +            val parentCompanions = allParents.flatMap { _ match
`_ match` can be ommited in such case

2020-10-22 19:31 UTC, romanowski commented on src/main/scala/dotty/dokka/transformers/ImplicitMembersExtensionTransformer.scala
> +            val implictSources = outerMembers ++ companion.toSeq ++ parentCompanions // We can expand this on generic etc.
I think we should create an issue and mentioned it here with `// TODO (#issue_no): We can expand this on generic etc.` style of comment

2020-10-27 18:26 UTC, merged